name: Github-Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: devops-commands-app
    runs-on:  self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v6
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Verify Node Version
        run:  node -v

      - name: Install Dependencies
        run:  npm install
      
      - name: Build Application
        run:  npm run build
      
      - name: Docker image build
        run:  docker image build -t devops-cmd-app:v1.0 .
      
      - name: Docker Images
        run:  socker iamge ls
